Fix OSX compat error
/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sphinxcontrib/images.py:23: RemovedInSphinx17Warning: sphinx.util.compat.Directive is deprecated and will be removed in Sphinx 1.7, please use the standard library version instead.
  from sphinx.util.compat import Directive

Extension error:
Could not import extension sphinxcontrib.images (exception: cannot import name 'make_admonition')
make: *** [html] Error 1